### ISSUE TITLE
[REQUEST] Change font colour on runemate

### ISSUE THREAD

**Issue by ozdv** [JohnRThomas/Exia-Mining-All-In-One#27]
In description, the font colour is yellow, with a white background, you can hardly read.  Could you change to a darker colour?

**Comment by JohnRThomas** [comment]
I usually use the dark theme which is why it is how it is. I'll find something that works well on both themes. Thanks for the report. :)

**Comment by JohnRThomas** [comment]
I changed all of the yellow to blue.
