### ISSUE TITLE
OSRSLocation change from IDS to Colors.

### ISSUE THREAD

**Issue by ghost** [JohnRThomas/Exia-Mining-All-In-One#4]
Fixed. Please merge: https://gist.github.com/Puz3/48539088fd878d9c42db

**Comment by JohnRThomas** [comment]
I've implemented this already. Also, your code does not look at the substitutions, which is what is important, not the default Colors.

**Comment by JohnRThomas** [comment]
Also, you can be made a contributor on the repository if you fork off and create a pull request instead of just posting the gist.
