### ISSUE TITLE
[REQUEST]Barbarian Village

### ISSUE THREAD

**Issue by JohnRThomas** [JohnRThomas/Exia-Mining-All-In-One#9]
Add Barbarian Village to OSRS
Add Barbarian Village to RS3

**Comment by JohnRThomas** [comment]
This is currently in testing. It seems the paths like to null point every now and then. We're searching for the cause.

**Comment by Kneckter** [comment]
Created the RS3 Barbarian village code. Still investigating the null pointer error.

**Comment by Kneckter** [comment]
Added a fix for the null pointer error. Testing it.

**Comment by JohnRThomas** [comment]
I think I fixed the null pointer issue, it was an issue with ViewportPath.getNext returning null sometimes. Barbarian Village on OSRS has been released.
RS3 still needs to be implemented.

**Comment by JohnRThomas** [comment]
RS3 has been added in commit:
f15635ca6d9c028b766d6a41adac2454db1e6798

Thanks.
